### ISSUE TITLE
Question regarding openal repo

### ISSUE THREAD

**Issue by NOOTLORD** [zenakuten/UT2004Tools#1]
Yes yes i am aware this is not the repo i have a question about but i can't submit a issue on your fork of openal 🤪

So on 11-3-2024 i send you a email with a question regarding your openal fork/fix for the 64-bit openal dll, but i didn't received a reply yet so i am curious if the yahoo email on your profile is still in use 😅

Hope to hear from you soon regarding this!

Kind regards
NOOTLORD

**Comment by zenakuten** [comment]
My profile email is correct.  I didn't see any email from you on 11-3-2024.  What's the question?

**Comment by NOOTLORD** [comment]
Good to know, no problem :D My question is why your version of openal sounds so muffled compared to the original and a random fixed dll i found on some archive. i attached some some clips in that original email so you can hear the difference.

So its all boils down to is there a setting that i can tweak to make it more like the original? The sounds sound to muffled even with the suggested options turned on.

*i just resend the email again, maybe it got stuck somewhere or could be that it gets marked as spam because it has a .flac files in it idk*
